# Generated by Django 3.2.5 on 2022-02-19 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodProvideRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meal_time', models.CharField(choices=[('BF', 'Breakfast'), ('LN', 'Lunch'), ('DN', 'Dinner')], max_length=2)),
                ('is_pending', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('food_item_count', models.IntegerField(default=0)),
                ('is_veg', models.BooleanField(default=True)),
                ('is_packed', models.BooleanField(default=False)),
                ('prep_time', models.FloatField(default=0)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=6)),
                ('phone_number', models.CharField(max_length=10)),
                ('lattitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FoodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('food_provide_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.foodproviderequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
